/**
 * Chronos API
 * API documentation for the Chronos application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Booking {
    'bookingDate': string;
    'bookingTime': string;
    'createdAt': Date;
    'durationMinutes': number;
    'guestEmail'?: string | null;
    'guestName'?: string | null;
    'guestPhone'?: string | null;
    'id': number;
    'notes'?: string | null;
    'serviceId': number;
    'status': string;
    'tenantId': number;
    'updatedAt': Date;
    'userId'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bookingDate",
            "baseName": "booking_date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "bookingTime",
            "baseName": "booking_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "durationMinutes",
            "baseName": "duration_minutes",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "guestEmail",
            "baseName": "guest_email",
            "type": "string",
            "format": ""
        },
        {
            "name": "guestName",
            "baseName": "guest_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "guestPhone",
            "baseName": "guest_phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceId",
            "baseName": "service_id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "tenantId",
            "baseName": "tenant_id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return Booking.attributeTypeMap;
    }

    public constructor() {
    }
}
