/**
 * Chronos API
 * API documentation for the Chronos application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BookingWithDetails {
    'bookingDate': string;
    'bookingTime': string;
    'id': number;
    'notes'?: string | null;
    'serviceDuration': number;
    'serviceName': string;
    'status': string;
    'userEmail': string;
    'userName': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bookingDate",
            "baseName": "booking_date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "bookingTime",
            "baseName": "booking_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceDuration",
            "baseName": "service_duration",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "serviceName",
            "baseName": "service_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "userEmail",
            "baseName": "user_email",
            "type": "string",
            "format": ""
        },
        {
            "name": "userName",
            "baseName": "user_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BookingWithDetails.attributeTypeMap;
    }

    public constructor() {
    }
}
